"""initial schema

Revision ID: aa5978af8c40
Revises: 
Create Date: 2026-07-23 16:17:05.919860

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = 'aa5978af8c40'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('admins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('google_subject_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_subject_id')
    )
    op.create_table('application_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chat_department_confidence_threshold', sa.Float(), nullable=False),
    sa.Column('chat_department_gap_threshold', sa.Float(), nullable=False),
    sa.Column('chunk_size_tokens', sa.Integer(), nullable=False),
    sa.Column('chunk_overlap_tokens', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('admin_id', sa.Uuid(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    op.create_table('chat_conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('admin_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drive_connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('admin_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('google_account_email', sa.String(), nullable=True),
    sa.Column('google_account_sub', sa.String(), nullable=True),
    sa.Column('access_token_encrypted', sa.String(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.String(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.String(), nullable=True),
    sa.Column('root_folder_id', sa.Uuid(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_files_discovered', sa.Integer(), nullable=False),
    sa.Column('total_indexed', sa.Integer(), nullable=False),
    sa.Column('total_failed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['root_folder_id'], ['drive_folders.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_id')
    )
    op.create_table('google_oauth_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('code_verifier', sa.String(), nullable=False),
    sa.Column('flow_type', sa.String(), nullable=False),
    sa.Column('redirect_uri', sa.String(), nullable=False),
    sa.Column('admin_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('response_type', sa.String(), nullable=True),
    sa.Column('detected_department', sa.String(), nullable=True),
    sa.Column('detected_topic', sa.String(), nullable=True),
    sa.Column('suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drive_folders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('drive_connection_id', sa.Uuid(), nullable=False),
    sa.Column('google_folder_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('parent_google_folder_id', sa.String(), nullable=True),
    sa.Column('is_root', sa.Boolean(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drive_connection_id'], ['drive_connections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drive_connection_id', 'google_folder_id')
    )
    op.create_table('sync_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('drive_connection_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('processed_files', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('current_filename', sa.String(), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drive_connection_id'], ['drive_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('drive_connection_id', sa.Uuid(), nullable=False),
    sa.Column('last_sync_run_id', sa.Uuid(), nullable=True),
    sa.Column('google_file_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('folder_path', sa.String(), nullable=False),
    sa.Column('drive_folder_id', sa.Uuid(), nullable=True),
    sa.Column('drive_link', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('classification_reason', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('storage_key', sa.String(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('ocr_applied', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('important_dates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('people', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('companies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drive_connection_id'], ['drive_connections.id'], ),
    sa.ForeignKeyConstraint(['drive_folder_id'], ['drive_folders.id'], ),
    sa.ForeignKeyConstraint(['last_sync_run_id'], ['sync_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_file_id')
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index')
    )
    op.create_table('chat_citations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('document_name', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_embeddings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('embedding_model', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id')
    )
    op.create_index(
        'ix_document_embeddings_embedding_hnsw',
        'document_embeddings',
        ['embedding'],
        unique=False,
        postgresql_using='hnsw',
        postgresql_with={'m': 16, 'ef_construction': 64},
        postgresql_ops={'embedding': 'vector_cosine_ops'},
    )
    op.execute(
        "CREATE INDEX ix_document_chunks_content_fts ON document_chunks "
        "USING gin (to_tsvector('english', content))"
    )
    op.execute(
        "CREATE INDEX ix_documents_extracted_text_fts ON documents "
        "USING gin (to_tsvector('english', extracted_text))"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_documents_extracted_text_fts")
    op.execute("DROP INDEX IF EXISTS ix_document_chunks_content_fts")
    op.drop_index('ix_document_embeddings_embedding_hnsw', table_name='document_embeddings')
    op.drop_table('document_embeddings')
    op.drop_table('chat_citations')
    op.drop_table('document_chunks')
    op.drop_table('documents')
    op.drop_table('sync_runs')
    op.drop_table('drive_folders')
    op.drop_table('chat_messages')
    op.drop_table('google_oauth_states')
    op.drop_table('drive_connections')
    op.drop_table('chat_conversations')
    op.drop_table('auth_sessions')
    op.drop_table('application_settings')
    op.drop_table('admins')
    # ### end Alembic commands ###
