from typing import Protocol


class StorageProvider(Protocol):
    async def upload(self, key: str, data: bytes, content_type: str) -> str: ...

    async def download(self, key: str) -> bytes: ...

    async def delete(self, key: str) -> None: ...

    async def get_presigned_url(self, key: str, expires_in: int = 300) -> str: ...
